<?php return array (
  'React\\Promise\\CancellationQueueTest' => 'CancellationQueueTest.php',
  'React\\Promise\\DeferredTest' => 'DeferredTest.php',
  'React\\Promise\\FulfilledPromiseTest' => 'FulfilledPromiseTest.php',
  'React\\Promise\\FunctionAllTest' => 'FunctionAllTest.php',
  'React\\Promise\\FunctionAnyTest' => 'FunctionAnyTest.php',
  'React\\Promise\\FunctionMapTest' => 'FunctionMapTest.php',
  'React\\Promise\\FunctionRaceTest' => 'FunctionRaceTest.php',
  'React\\Promise\\FunctionReduceTest' => 'FunctionReduceTest.php',
  'React\\Promise\\FunctionRejectTest' => 'FunctionRejectTest.php',
  'React\\Promise\\FunctionResolveTest' => 'FunctionResolveTest.php',
  'React\\Promise\\FunctionSomeTest' => 'FunctionSomeTest.php',
  'React\\Promise\\LazyPromiseTest' => 'LazyPromiseTest.php',
  'React\\Promise\\PromiseTest' => 'PromiseTest.php',
  'React\\Promise\\RejectedPromiseTest' => 'RejectedPromiseTest.php',
);